### ISSUE TITLE
lapack_complex_float and lapack_complex_double are not exported from module

### ISSUE THREAD

**Issue by andreaspetrovic** [SciNim/nimlapack#3]
Hey there. Maybe I'm getting something wrong, but it seems that both lapack_complex_float, and lapack_complex_double are not exported from the module. Hence, calling complex procs like cgesdd, does not work. When I manually mark them with an asterisk (and re and im too), everything works fine.
Cheers,
Andreas

**Comment by Vindaar** [comment]
Thanks for the report! I exported them in #4 and pushed a new tag.

**Comment by andreaspetrovic** [comment]
Thanks!
